# Generated by Django 5.0 on 2024-01-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_cover_photos_user_profile_picture_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line',
            new_name='address',
        ),
    ]
