# Generated by Django 5.0 on 2024-01-31 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('vendor', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Raw Item Name')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Description')),
                ('is_deleted', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='raw_items',
            field=models.ManyToManyField(blank=True, to='menu.rawitem'),
        ),
    ]
