# Generated by Django 5.0 on 2024-02-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rawitem_fooditem_raw_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
