# Generated by Django 5.0 on 2024-01-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_alter_cart_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(db_index=True, max_length=20, unique=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax Percentage (%)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
            },
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Percentage (%)'),
        ),
    ]
